id: P007858
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24309
  title: རཱ་བྷིན་ཌ་ར་ན་ཐ་ཊེ་གོར།
  author: ''
  volumes:
    16acde26b46c41e9b02064c82aadcc6e:
      image_group_id: I1KG24353
      title: ''
      volume_number: 1
      total_pages: 32
ebook_metadata:
  title: རཱ་བྷིན་ཌ་ར་ན་ཐ་ཊེ་གོར།
  author: ''
  sku: P007858
  cover: cover.jpg
  layers:
  - pagination
